- hosts: all
  become: yes
  collections:
    - community.docker

  roles:
    - geerlingguy.pip

  tasks:
    - name: Install specific version of requests
      pip:
        name: requests==2.31.0
        state: present
      tags: install

    - name: Install docker module via pip
      pip:
        name: docker
      tags: install

    - name: Create env file directory
      file:
        path: "{{ destination_path }}"
        state: directory
      tags: deploy

    - name: Copy env file template
      template:
        src: .env
        dest: "{{ redmine_env_file }}"
      tags: deploy

    - name: Run Redmine
      community.docker.docker_container:
        name: redmine
        image: redmine
        restart_policy: always
        state: started
        ports:
          - "80:3000"
        env_file: "{{ redmine_env_file }}"
      tags: deploy

    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.dd.agent
      vars:
        datadog_api_key: "{{ datadog_key }}"
        datadog_site: "{{ datadog_domain }}"
        datadog_checks:
          http_check:
            init_config:
            instances:
              - name: app_check
                url: http://localhost
      tags: deploy